async def send_file(bot, chat_id: int, file_path: str, file_name: str) -> None:
    # ... existing send_file code ...

def parse_delay_from_filename(filename: str) -> Optional[int]:
    # ... existing parse_delay code ...